export const labels = {
  consumptionDetails: "Consumption Details",
  consumptionDetailOwnLicense: "Consumption Details (My Own License)",
  logs: "Logs",
  searchByMonth: "Search by Month",
  searchByYear: "Search by Year",
  accountId: "Account Code",
  accountName: "Account Name",
  activePackageName: "Active Package Name",
  consumptionDueAmount: "Consumption Due Amount",
  dueMonth: "Due Month",
  activationDate: "Activation Date",
  download: "Export PDF",
  excelText: "Export Excel",
  filename: "ConsumptionReport.pdf",
  packageRemaining: "Package Remaining",
  pleaseSelectYear: "Please select year!",
  total: "Total",
  clientSubscription: "Client Subscriptions",
  searchClientName: "Search Client Name",
  searchPackageName: "Search Package Name",
  selectPackageStatus: "Select Package Status",
  annualPackages: "Annual Packages",
  prepaidPackages: "Prepaid Packages",
  packageName: "Package Name",
  price: "Price",
  transactionLimit: "Transaction Limit",
  transactionConsumption: "Transaction Consumption",
  availableAmount: "Available Amount",
  priceConsumption: "Price Consumption",
  dueDate: "Due Date",
  status: "Status",
  accountID: "Account ID",
  back: "Back",
  packageDetail: "Package Detail",
  logsDetail: "Logs Detail",
  serviceName: "Service Name",
  serviceUrl: "Service Url",
  transactionDate: "Transaction Date",
  requestTime: "Request Time",
  responseTime: "Response Time",
  request: "Request",
  response: "Response",
  fromDate: "From Date",
  toDate: "To Date",
  consumptionReportTitle: "Consumption Detail of ",
  consumptionReportTitleForOwnCredentails:
    "Consumption Details (My Own License) of ",
};
