export const labels = {
  users: "Users",
  pageNotFound: "Page Not Found",
  signIn: "Log In",
  uapi: "UAPI Where Integration Meets Innovation",
  forgetPassword: "ForgetPassword",
  resetPassword: "Reset Password",
  setPassword: "Set Password",
  swaggerPage: "Swagger",
  profile: "Profile",
  services: "Services",
  searchPlaceholder: "Search here...",
  yes: "Yes",
  no: "No",
  confirmText: "Confirm",
  cancelText: "Cancel",
  comingSoon: "Coming soon",
  packageManagement: "Package Management",
  invoiceManagement: "Invoice Management",
  subAccountManagement: "SubAccount Management",
  rolesManagement: "Role Management",
  myInvoices: "My Invoices",
  rolesAndPermissions: "Roles and Permissions",
  userManagement: "User Management",
  reports: "Reports",
  logReports: "LogsReports",
  logs: "Logs",
  consumptionDetails: "Consumption Details",
  consumptionDetailOwnLicense: "Consumption Details (My Own License)",
  hideMenu: "Hide Menu",
  view: "View",
  edit: "Edit",
  delete: "Delete",
  annualSubscriptionTiers: "Annual Subscription Tiers",
  serviceBundles: "Services Bundles",
  accessDenied: "Access Denied",
  backToLogin: "Back to Home",
  forbiddenText: "Sorry, you do not have permission to view this resource.",
  footerText: "",
  home: "Home",
  dashboard: "Dashboard",
  auditLogs: "Audit Logs",
  subAccounts: "Sub Account Management",
  accountSwitchConfirmation: "Are you sure you want to switch to main account?",
  callbackLogs: "Callback Logs",
};
