export const labels = {
  addUser: "Create User",
  sortButtonText: "Sort",
  statusButtonText: "Status",
  usersButtonText: "Users",
  usersList: "User",
  id: "ID",
  firstName: "First Name",
  lastName: "Last Name",
  userName: "User Name",
  nationalId: "National ID",
  arabicName: "Arabic Name",
  email: "Email",
  contactNo: "Mobile Number",
  userType: "User Type",
  company: "Company",
  status: "Status",
  updateUser: "Edit User",
  viewUser: "View User",
  password: "Password",
  confirmPassword: "Confirm Password",
  manageUsers: "User Management",
  userRole: "Role",
  save: "Save",
  editUsers: "Edit Users",
  userInfo: "User Info",
  userExists: "Username already exist!",
  userEmailExists: "User email already exist!",
  userDeleteConfirmation: "Are you sure you want to delete this user, ",
  searchUsers: "Search with First Name, Last Name and Email",
  shouldNotBeBlank: "This field cannot be left blank",
  maxFirstName: "First name should be less than 10 characters",
  maxLastName: "Last name should be less than 10 characters",
  nationalIdShouldContainOnlyDigits: "National ID Should contain only digits",
  nationalIdLimit: "National id should be exactly 10 characters",
  usernameLimit: "username should be less than 50 characters",
  invalidEmail: "Invalid email address",
  emailLimit: "Email should be limited to max 50 characters",
  nationalIdShouldNumeric: "National id should only be numeric",
  contactPattern: "Mobile number should starts with the 05",
  invalidContact:
    "Invalid contact number. The number should start with 05 and max 10 digit long",
  role: "Role",
  isActive: "status",
  active: "Active",
  inActive: "Inactive",
  cancel: "Cancel",
  forbiddenText:
    "Access denied! Sorry, you do not have permission to perform this operation.",
  useMainAccountBundles:
    "Use the annaul and service bundle from the main account",
};
