export const labels = {
  addpackage: "Add Package",
  accountName: "Account Name",
  subAccountName: "Sub Account Name",
  selectServicesPackagesStatus: "Select Services Package Status",
  availableAmountUpdated: "Available amount updated until previous month",
  priceConsumptionUpdated: "Price consumption updated until previous month",
  annualPackage: "Annual Package",
  servicesPackage: "Services Package",
  packageManagment: "Package Management",
  searchAnnualPackageName: "Search Annual Package Name",
  packageName: "Package Name",
  annualPackageTransactionConsumptionMessage:
    "Annual package transaction consumption is up to date",
  validity: "Validity",
  packagePrice: "Package Price",
  duration: "Duration",
  transactionLimit: "Transaction Limit",
  addPackage: "Add package",
  editPackage: "Edit Package",
  viewPackage: "View Package",
  submit: "Submit",
  generateInvoice: "Generate Invoice",
  choosePlan: "Choose Your Pricing Plan",
  postpaidBundle: "Postpaid Bundle",
  prepaidBundles: "Prepaid Bundles",
  planDescription:
    "Our tiered pricing plans provide the perfect balance of feature and affordability. To Activate Service bundles, choose any of the annual subscription package.",
  packageDeleteConfirmation: "Are you sure you want to delete this package?",
  addNewAnnualPackage: "Add New Annual Subscription Tier",
  addNewServiceBundle: "Add New Service Bundle",
  save: "Save",
  cancel: "Cancel",
  packageSelectionMessage: "Are you sure you want to select this package?",
  postPaidSelectionMessage:
    "Are you sure you want to subscribe Postpaid package",
  annualPackageActivationMessage:
    "The Annual Package will be activated on the `Activation date`.",
  serviceBundleAnnualActivationMessage:
    "The Service Bundle will be activated on the `Activation date`.",
  proceedMessage: "The Invoice will be generated. Do you want to proceed?",
  allProcessBeforeTaxes: "(All prices are before taxes.)",
  activationDate: "Activation Date",
  packageActivationRequest:
    "Package Activation request sent! Please check the invoice section.",
  postPaidPackageActivated: "Postpaid Package is activated!",
  price: "Price",
  annualPackages: "Annual Packages",
  prepaidPackages: "Prepaid Packages",
  transactionConsumption: "Transaction Consumption",
  availableAmount: "Available Amount",
  priceConsumption: "Price Consumption",
  dueDate: "Activation date",
  status: "Status",
  searchPackageName: "Search Services Package Name",
  active: "Active",
  expired: "Expired",
  paymentPending: "Payment Pending",
  packageDetail: "Package Detail",
  packageID: "Package ID",
  back: "Back",
  selectPackageStatus: "Select Annual Package Status",
  subscribedPackages: "Subscribed Packages",
  availablePackages: "Available to add for the first time or to upgrade",
  reNewPackage: "Renew Package",
  subscribedPrepaidBundles: "Subscribed Prepaid Bundles",
  availablePrepaidBundles: "Available Prepaid Bundles",
  selectedPackageNotAvailable: "Selected Package is not available for renewal!",
  forbiddenText:
    "Access denied! Sorry, you do not have permission to perform this operation.",
  servicePostpaidPackage: "Postpaid Package Subscribed",
  postPaidPackageSubscribedText: "Postpaid Package Activation Date : ",
};
