export const labels = {
  auditLogs: "Audit Logs",
  download: "Export PDF",
  excelText: "Export Excel",
  account: "Account",
  module: "Modules",
  activity: "Activity",
  activityDate: "Activity Date/Time",
  searchAccountName: "Search Account Name",
  accountName: "Account Name",
  selectModule: "Select Module",
  moduleName: "Module",
  fromDate: "From Date",
  toDate: "To Date",
  userName: "Username",
  selectUser: "Select User",
  user: "User",
  auditLogsDetail: "Audit Log Detail",
  oldValues: "Form Values Audit Log",
  back: "Back",
  operation: "Operation",
  path: "Path",
  oldValue: "Old Value",
  newValue: "New Value",
  noDataFound: "No record found!",
  exportError:
    "Audit logs cannot be exported at this time. Please try again later.",
};
