export const labels = {
  signInPage: "SignIn Page",
  passwordText: "Password",
  username: "Username ",
  signIn: "Sign In",
  remember: "Remember me",
  forgetPassword: "Forgot Password?",
  usernameKey: "username",
  passwordKey: "password",
  shouldNotBeBlank: "This field cannot be left blank",
  atLeastEightCharacter: "At least 8 character(s)",
  maxTeventyCharacters: "Maximum of 20 character(s) allowed",
  atLeastOneNumber: "At least 1 number",
  atLeastOneSpecialCharacter: "At least 1 special character",
  atLeastOneLowercase: "At least 1 lowercase letter(s)",
  atLeastOneUppercase: "At least 1 uppercase letter(s)",
  invalidEmail: "Invalid email address",
  welcomeBack: "Welcome Back",
  forgotPassword: "Forgot Password?",
  resetPassword: "Reset Password?",
  setPassword: "Set Password?",
  resetPasswordDetail: "Enter a new password for your account.",
  setPasswordDetail: "Secure your account with the new password!",
  forgotPasswordDetail: "Enter your registered email ID to reset the password.",
  sendBtn: "Send",
  cancel: "Cancel",
  emailSend:
    "Reset password email sent successfully. Please check your inbox for further instructions.",
  passwordResetSuccess: "Password reset successfully. Please Login again!",
  passwordSetSuccess: "Password set successfully. Please Login again!",
};
