version: '3.7'

services:
  apihub-core-db:
    container_name: apihub-core-db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=apihubdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-apihub-vol:
