spring:
  flyway:
    locations:
      - classpath:/db/migration/generic
      - classpath:/db/migration/postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${APIHUB_DATABASE_HOST:}:${APIHUB_DATABASE_PORT:5432}/${APIHUB_DATABASE_NAME:}
    password: ${APIHUB_DATABASE_PASSWORD:}
    username: ${APIHUB_DATABASE_USERNAME:}
logging:
 level:
   ROOT: INFO
