spring:
  devtools:
    restart:
      enabled: true
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
#         type:
#           descriptor:
#             sql=TRACE:

logging:
 level:
   ROOT: DEBUG
