export const labels = {
  createSubAccount: "Create Sub Account",
  updateSubAccount: "Update Sub Account",
  viewSubAccount: "View Sub Account",
  subAccounts: "Sub Account Management",
  searchSubAccount: "Search with sub account name",
  accountCode: "Account Code",
  subAccountName: "Sub Account Name",
  websiteURL: "Website URL",
  email: "Email",
  postPaidSubscribed: "PostPaid Subscribed",
  useAccountBundles: "Use Main Account Bundles",
  status: "Status",
  adminInfo: "Admin Information",
  settings: "Settings",
  projectName: "Product/Project Name",
  description: "Description",
  firstName: "First Name",
  lastName: "LastName",
  nationalId: "National Id",
  username: "User Name",
  mobileNumber: "Mobile Number",
  services: "Services",
  paymentMethod: "Payment Method",
  bundleType: "bundle Type",
  shouldNotBeBlank: "This field cannot be left blank",
  selectAnnualPackage: "Please select atleast one Annual Package",
  selectServicePackage: "Please select atleast one Service Bundle",
  selectServiceError: "Please select atleast one service",
  maxCompanyDescription: "Description should be less than 30 characters",
  maxFirstName: "First name should be less than 10 characters",
  maxLastName: "Last name should be less than 10 characters",
  nationalIdShouldNumeric: "National id should only be numeric",
  nationalIdLimit: "National id should be exactly 10 characters",
  usernameLimit: "username should be less than 50 characters",
  invalidEmail: "Invalid email address",
  emailLimit: "Email should be limited to max 50 characters",
  invalidContact:
    "Invalid contact number. The number should start with 05 and max 10 digit long",
  contactPattern: "Mobile number should starts with the 05",
  serviceLogging: "Service(s) Logging",
  servicesBundles: "Services Bundle(s)",
  allowPostpaidPackages: "Allow Postpaid Packages",
  postPackageToolTip:
    "Allow to display the postpaid packages in the developer portal",
  annualSubscriptionTier: "Annual Subscription Tier(s)",
  active: "Active",
  inActive: "Inactive",
  allServiceProviders: "All Service Providers",
  loggingEnabledServiceProviders: "Logging Enabled Service Providers",
  allServices: "All Services",
  selectedServices: "Selected Service",
  updateAccount: "Update SubAccount",
  createAccount: "Create SubAccount",
  back: "Back",
  save: "Save",
  next: "Next",
  cancel: "cancel",
  useMainAccountBundles:
    "Use the annual and service bundle from the main account",
  mustBeTextOnly: "Company name should only consist of text characters",
  maxCompanyName: "Company name should be less than 20 characters",
  companyDeleteConfirmation:
    "Are you sure you want to delete this sub account?",
  accountSwitchConfirmation:
    "Are you sure you want to switch to this sub account?",
  switchAccount: "Switch Account",
};
