version: '3.7'

services:
  apihub-accounts-db:
    container_name: apihub-accounts-db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=apihubaccountsdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myaccountuser'
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-apihub-accounts-vol:
