export const labels = {
  callbackLogs: "Callback Logs",
  download: "Export PDF",
  excelText: "Export Excel",
  inboundEndpoint: "Inbound Endpoint",
  outboundUrl: "Outbound URL",
  outboundResponse: "Outbound Response",
  createdAt: "Created At",
  fromDate: "From Date",
  toDate: "To Date",
  searchCompany: "Search Company",
  companyName: "Company Name",
  serviceName: "Service Name",
  searchService: "Search Service",
  selectCompanyName: "Select Company Name",
  selectServiceName: "Select Service Name",
  callbackLogsDetail: "Callback Log Detail",
  oldValues: "Form Values Callback Log",
  back: "Back",
  operation: "Operation",
  outboundResponseReceivedAt: "Outbound Response Receieved At",
  inboundRequestData: "Inbound Request Data",
  outboundRequestData: "Outbound Request Data",
  error: "Error",
  apiError: "API Error",
  inboundRequestReceivedAt: "Inbound Request Receieved At",
  path: "Path",
  noDataFound: "No record found!",
  exportError:
    "Callback logs cannot be exported at this time. Please try again later.",
};
