export const labels = {
  myInvoices: "My Invoices",
  searchPackageName: "Search Package Name",
  invoiceNo: "Invoice No",
  sadadInvoiceNo: "Sadad Invoice",
  invoiceType: "Invoice Type",
  packageName: "Package Name",
  amount: "Amount",
  dueDate: "Invoice Issue Date",
  status: "Status",
  taxInvoice: "Tax Invoice",
  selectInvoiceStatus: "Select Invoice Status",
  selectInvoiceType: "Select Invoice Type",
  download: "Export PDF",
  excelText: "Export Excel",
  exportError:
    "Reports cannot be exported at this time. Please try again later.",
  addpackage: "Add Package",
  accountName: "Account Name",
  subAccountName: "Sub Account Name",
  uploadInvoice: "Upload Invoice",
  fileSizeText: "File is too large",
  fileType: "File must be a PDF and should not exceed 1MB in size.",
  fileDuplicate: "duplicate file!",
  dragFileText: "Please Drag & Drop the file",
  uploadText: "Upload",
  fileText: "File",
  save: "Save",
  fileUploaded: "File Uploaded",
  slipStatus: "Slip Status",
  slipTitle: "Slip",
};
